// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSMSystem.Data;

#nullable disable

namespace PSMSystem.Migrations
{
    [DbContext(typeof(PsmDbContext))]
    [Migration("20260825215152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSMSystem.Models.AvanceTrabajo", b =>
                {
                    b.Property<int>("IdAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_avance");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvance"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("etapa");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdOrdenTrabajo")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_trabajo");

                    b.HasKey("IdAvance");

                    b.HasIndex("IdOrdenTrabajo");

                    b.ToTable("AvanceTrabajo", null, t =>
                        {
                            t.HasCheckConstraint("CK_AvanceTrabajo_Etapa", "[etapa] IN ('Diagnóstico', 'Reparación', 'Espera de repuestos', 'Finalización')");
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detallefactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdRepuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdRepuesto");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.DetallePresupuesto", b =>
                {
                    b.Property<int>("IdDetallePresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detallepresupuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePresupuesto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_presupuesto");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetallePresupuesto");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdRepuesto");

                    b.ToTable("DetallePresupuesto", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoFactura", b =>
                {
                    b.Property<int>("IdEstadoFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoFactura"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoFactura");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoFactura", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoFactura = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoFactura = 2,
                            Nombre = "Pagada"
                        },
                        new
                        {
                            IdEstadoFactura = 3,
                            Nombre = "Vencida"
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoOrdenTrabajo", b =>
                {
                    b.Property<int>("IdEstadoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_orden");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoOrden"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoOrden");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoOrdenTrabajo", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoOrden = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoOrden = 2,
                            Nombre = "En proceso"
                        },
                        new
                        {
                            IdEstadoOrden = 3,
                            Nombre = "Esperando repuestos"
                        },
                        new
                        {
                            IdEstadoOrden = 4,
                            Nombre = "Finalizada"
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoPresupuesto", b =>
                {
                    b.Property<int>("IdEstadoPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_presupuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoPresupuesto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoPresupuesto");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoPresupuesto", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoPresupuesto = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoPresupuesto = 2,
                            Nombre = "Aprobado"
                        },
                        new
                        {
                            IdEstadoPresupuesto = 3,
                            Nombre = "Rechazado"
                        },
                        new
                        {
                            IdEstadoPresupuesto = 4,
                            Nombre = "Facturado"
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoTurno", b =>
                {
                    b.Property<int>("IdEstadoTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoTurno"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstadoTurno");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadoTurno", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoTurno = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoTurno = 2,
                            Nombre = "En progreso"
                        },
                        new
                        {
                            IdEstadoTurno = 3,
                            Nombre = "Finalizado"
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateOnly?>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdEstadoFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_factura");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_presupuesto");

                    b.Property<decimal?>("Iva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iva");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdEstadoFactura");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.MovimientoStock", b =>
                {
                    b.Property<int>("IdMovimientoStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimientostock");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimientoStock"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    b.Property<int>("IdTipoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_movimiento");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observacion");

                    b.HasKey("IdMovimientoStock");

                    b.HasIndex("IdRepuesto");

                    b.HasIndex("IdTipoMovimiento");

                    b.ToTable("MovimientoStock", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("IdOrdenTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ordentrabajo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenTrabajo"));

                    b.Property<string>("DiagnosticoInicial")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("diagnosticoinicial");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entregaestimada");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateOnly?>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstadoOrden")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_orden");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("MotivoIngreso")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("motivo_ingreso");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdOrdenTrabajo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoOrden");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("OrdenTrabajo", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medio_pago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdPago");

                    b.HasIndex("IdFactura");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.Presupuesto", b =>
                {
                    b.Property<int>("IdPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_presupuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPresupuesto"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdEstadoPresupuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_presupuesto");

                    b.Property<int>("IdOrdenTrabajo")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_trabajo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdPresupuesto");

                    b.HasIndex("IdEstadoPresupuesto");

                    b.HasIndex("IdOrdenTrabajo");

                    b.ToTable("Presupuesto", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.Repuesto", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_repuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepuesto"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("proveedor");

                    b.Property<int>("StockActual")
                        .HasColumnType("int")
                        .HasColumnName("stock_actual");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.HasKey("IdRepuesto");

                    b.ToTable("Repuesto", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.TipoMovimientoStock", b =>
                {
                    b.Property<int>("IdTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMovimiento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoMovimiento");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoMovimientoStock", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoMovimiento = 1,
                            Nombre = "Ingreso"
                        },
                        new
                        {
                            IdTipoMovimiento = 2,
                            Nombre = "Egreso"
                        },
                        new
                        {
                            IdTipoMovimiento = 3,
                            Nombre = "Devolución"
                        },
                        new
                        {
                            IdTipoMovimiento = 4,
                            Nombre = "Compra"
                        });
                });

            modelBuilder.Entity("PSMSystem.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstadoTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_turno");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("motivo");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoTurno");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<int?>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateOnly?>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("patente");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Vehiculo", (string)null);
                });

            modelBuilder.Entity("PSMSystem.Models.AvanceTrabajo", b =>
                {
                    b.HasOne("PSMSystem.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("AvancesTrabajo")
                        .HasForeignKey("IdOrdenTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("PSMSystem.Models.DetalleFactura", b =>
                {
                    b.HasOne("PSMSystem.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.Repuesto", "Repuesto")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factura");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("PSMSystem.Models.DetallePresupuesto", b =>
                {
                    b.HasOne("PSMSystem.Models.Presupuesto", "Presupuesto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.Repuesto", "Repuesto")
                        .WithMany("DetallesPresupuesto")
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Presupuesto");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("PSMSystem.Models.Factura", b =>
                {
                    b.HasOne("PSMSystem.Models.EstadoFactura", "EstadoFactura")
                        .WithMany("Facturas")
                        .HasForeignKey("IdEstadoFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.Presupuesto", "Presupuesto")
                        .WithMany("Facturas")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoFactura");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("PSMSystem.Models.MovimientoStock", b =>
                {
                    b.HasOne("PSMSystem.Models.Repuesto", "Repuesto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.TipoMovimientoStock", "TipoMovimiento")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("IdTipoMovimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repuesto");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("PSMSystem.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("PSMSystem.Models.Cliente", "Cliente")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.EstadoOrdenTrabajo", "EstadoOrden")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("IdEstadoOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.Turno", "Turno")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PSMSystem.Models.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoOrden");

                    b.Navigation("Turno");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PSMSystem.Models.Pago", b =>
                {
                    b.HasOne("PSMSystem.Models.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("PSMSystem.Models.Presupuesto", b =>
                {
                    b.HasOne("PSMSystem.Models.EstadoPresupuesto", "EstadoPresupuesto")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdEstadoPresupuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdOrdenTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPresupuesto");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("PSMSystem.Models.Turno", b =>
                {
                    b.HasOne("PSMSystem.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.EstadoTurno", "EstadoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("IdEstadoTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PSMSystem.Models.Vehiculo", "Vehiculo")
                        .WithMany("Turnos")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoTurno");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("PSMSystem.Models.Vehiculo", b =>
                {
                    b.HasOne("PSMSystem.Models.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PSMSystem.Models.Cliente", b =>
                {
                    b.Navigation("OrdenesTrabajo");

                    b.Navigation("Turnos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoFactura", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoOrdenTrabajo", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoPresupuesto", b =>
                {
                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("PSMSystem.Models.EstadoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("PSMSystem.Models.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PSMSystem.Models.OrdenTrabajo", b =>
                {
                    b.Navigation("AvancesTrabajo");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("PSMSystem.Models.Presupuesto", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("PSMSystem.Models.Repuesto", b =>
                {
                    b.Navigation("DetallesFactura");

                    b.Navigation("DetallesPresupuesto");

                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("PSMSystem.Models.TipoMovimientoStock", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("PSMSystem.Models.Turno", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("PSMSystem.Models.Vehiculo", b =>
                {
                    b.Navigation("OrdenesTrabajo");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
